### ISSUE TITLE
Improve error message when essential props are missing from the property drawer....

### ISSUE THREAD

**Issue by oatmealm** [nobiot/org-remark#47]
Not sure if this is related to the previous issue I've reported, but I've noticed that when the props  ~:org-remark-beg:~ and ~
:org-remark-end:~ are missing, when the mode is activated you see this unhelpful error:  "org-remark-highlights-load: Wrong type argument: stringp, nil"... now, I'm not sure why it was missing, but just in case it's possible to validate the existence of the essential props, it might be helpful...

**Comment by nobiot** [comment]
Yea, sorry I have been making changes. Should not have gone to main branch. I’m sending some more.

**Comment by nobiot** [comment]
I apologize. Im only connected to internet via my phone. I think Will need a couple of more days to stabilize all the changes with notes-sync. If you can, probably rolling back to 618d60393961f83f0e18881d970f070063064f13 would be probably better.

For now, i will keep going with fixing the main branch. My latest in my local looks more promising.

Again sorry for all the low-quality commits to main. Thank you for reporting. Ill need to be better with using dev branches for incubation

**Comment by nobiot** [comment]
Deleted my confusing previous comments. 

As I mention in https://github.com/nobiot/org-remark/issues/46#issuecomment-1365599482

I have rolled back the main to https://github.com/nobiot/org-remark/commit/618d60393961f83f0e18881d970f070063064f13. It should be more stable. All the latest changes are in PR https://github.com/nobiot/org-remark/pull/48.

You can manually remove :org-remark-note-body: from your notes. It should never been a property in notes files (now fixed in PR https://github.com/nobiot/org-remark/pull/48).

@oatmealm I really appreciate your sending these reports. Let me know if your notes are OK now. Let me know if you have more issues stemming from all these commits that went into the main prematurely.

**Comment by nobiot** [comment]
#51 has gone in with a bunch of fixes to round off the previous update. I believe this issue reported here is a one-off event and does not recur any longer. Please reopen/recreate if the issue persists.
